#!/usr/bin/env node
/*
Server-side executor (engine):
- Reads engine-input.json generated by client/prepare.js
- Intended to create/update issues and optionally sync Project V2

NOTE: This is a scaffold. It validates inputs and prints an execution plan.
Actual GH issue/project mutations will be implemented in the next iteration.
*/

const fs = require('fs');
const path = require('path');

function readJson(p) {
  return JSON.parse(fs.readFileSync(p, 'utf8'));
}

function main() {
  const args = process.argv.slice(2);
  const inIndex = args.indexOf('--input');
  const inputPath = (inIndex >= 0 && args[inIndex + 1]) ? args[inIndex + 1] : './tmp/engine-input.json';

  if (!fs.existsSync(inputPath)) {
    console.error('Engine input not found:', inputPath);
    process.exit(2);
  }

  const engine = readJson(inputPath);
  console.log('Engine version:', engine.version);
  console.log('Generated at:', engine.generatedAt);
  console.log('Owner:', engine.owner);
  console.log('Project URL:', engine.project && engine.project.url ? engine.project.url : '(none)');

  for (const t of engine.targets || []) {
    console.log('\nTarget:', t.repo);
    console.log('  enableProjectSync:', !!t.enableProjectSync);
    console.log('  tasks:', (t.tasks || []).length);
    console.log('  subtasks:', (t.subtasks || []).length);
  }

  console.log('\nNext step: implement gh issue ops + project field updates using this JSON as source of truth.');
}

main();
